name: Build iOS Project
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Briefcase
        run: |
          python -m pip install --upgrade pip
          pip install briefcase

      - name: Create iOS App
        run: briefcase create ios --no-input

      - name: Build iOS App
        run: briefcase build ios --no-input

      - name: Upload Xcode Project
        uses: actions/upload-artifact@v4
        with:
          name: FlashTimer-Xcode-Project
          # On récupère tout le dossier de build iOS
          path: build/flashtimer/ios/xcode/
